<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <brand>
        <headerColor>#0070D2</headerColor>
        <shouldOverrideOrgTheme>false</shouldOverrideOrgTheme>
    </brand>
    <formFactors>Small</formFactors>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <isOmniPinnedViewEnabled>false</isOmniPinnedViewEnabled>
    <label>Banking App</label>
    <navType>Standard</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>My_Account_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>My_Account__c</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>My_Account_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>My_Account__c</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>My_Account_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>My_Account__c</pageOrSobjectType>
        <recordType>My_Account__c.Company_Account</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>My_Account_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>My_Account__c</pageOrSobjectType>
        <recordType>My_Account__c.Company_Account</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>My_Account_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>My_Account__c</pageOrSobjectType>
        <recordType>My_Account__c.Individual_Account</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>My_Account_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>My_Account__c</pageOrSobjectType>
        <recordType>My_Account__c.Individual_Account</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <tabs>My_Account__c</tabs>
    <tabs>My_Payee__c</tabs>
    <tabs>Transaction__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>Banking_App_UtilityBar</utilityBar>
</CustomApplication>
